jobs:
  build:
    docker:
      - image: alekseyyaroslavcev/qt5-mingw32-dw2
    resource_class: small
    steps:
      - checkout
      - run: 
          command: |
            export PATH=/opt/mxe/usr/bin:$PATH
            qmake putTextIntoBitmap.pro
            make